// <auto-generated />
using System;
using DreamsAPI.Structure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DreamsAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("DreamsAPI.Structure.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CheckInDate = new DateTime(2026, 1, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            CheckOutDate = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2026, 1, 21, 17, 51, 29, 344, DateTimeKind.Utc).AddTicks(3447),
                            Email = "john.smith@example.com",
                            GuestName = "John Smith",
                            NumberOfGuests = 2,
                            RoomType = "Deluxe",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CheckInDate = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            CheckOutDate = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2026, 1, 21, 17, 51, 29, 344, DateTimeKind.Utc).AddTicks(3931),
                            Email = "mary@example.com",
                            GuestName = "Mary Johnson",
                            NumberOfGuests = 3,
                            RoomType = "Suite",
                            Status = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
